"""Public facade for the executable, inference-only v5 Study A audit."""

from .study_a_capture import (
    capture_phase2a_natural_observations,
    load_phase2a_child,
    load_phase2a_parents,
    run_phase2a_study_a,
)
from .study_a_execution import (
    load_gpu_checkpoint,
    load_natural_errors,
    require_study_a_authorization,
    require_t_adapter,
    run_study_a,
    summarize_study_a,
)
from .study_a_scenarios import (
    BASE_SHA256,
    CHECKPOINTS,
    GRAPH_AXES,
    OBSERVATION_PROMPT,
    OBSERVATION_PROMPT_VERSION,
    PHASE2A_PARENT_MANIFEST_SHA256,
    PROMPT_VERSION,
    RAW_ARCHIVE_MEMBER,
    RAW_ARCHIVE_SHA256,
    STUDY_A_ACK,
    T_ADAPTER_SHA256,
    StudyAScenario,
    build_phase2_study_a_scenarios,
    build_study_a_scenarios,
    sha256_file,
)

__all__ = [
    "BASE_SHA256",
    "CHECKPOINTS",
    "GRAPH_AXES",
    "OBSERVATION_PROMPT",
    "OBSERVATION_PROMPT_VERSION",
    "PHASE2A_PARENT_MANIFEST_SHA256",
    "PROMPT_VERSION",
    "RAW_ARCHIVE_MEMBER",
    "RAW_ARCHIVE_SHA256",
    "STUDY_A_ACK",
    "T_ADAPTER_SHA256",
    "StudyAScenario",
    "build_phase2_study_a_scenarios",
    "build_study_a_scenarios",
    "capture_phase2a_natural_observations",
    "load_gpu_checkpoint",
    "load_natural_errors",
    "load_phase2a_child",
    "load_phase2a_parents",
    "require_study_a_authorization",
    "require_t_adapter",
    "run_phase2a_study_a",
    "run_study_a",
    "sha256_file",
    "summarize_study_a",
]
