"""Regenerate the frozen configuration and evidence copies from the supplied audit archive.
This utility performs no training, rendering, external download or job submission.
Use only the original extracted MM_CORE_PRO_REVIEW_20261009 evidence directory.
"""
from pathlib import Path
import argparse,json,sys
from plan_contract import allocation_counts,seed_usage,PLAN_ID,rank
out=Path(__file__).resolve().parents[1]
parser=argparse.ArgumentParser(description=__doc__)
parser.add_argument('source_root',type=Path,help='Extracted original MM_CORE_PRO_REVIEW_20261009 archive')
args=parser.parse_args()
source=args.source_root.resolve()
if not (source/'audit/manifests/ENVIRONMENT.json').is_file():
    raise SystemExit('Source archive is missing audit/manifests/ENVIRONMENT.json')
env=json.loads((source/'audit/manifests/ENVIRONMENT.json').read_text())
freeze=json.loads((source/'audit/manifests/PRE_INFERENCE_FREEZE.json').read_text())
identity_fields=['model_id','model_revision','model_weights_hash','model_path','processor_hash','tokenizer_hash','chat_template_hash','chat_template_kwargs','chat_template_kwargs_hash','linear_kernel_identity_hash','attention_backend','dtype']
identity={k:freeze.get(k,env.get(k)) for k in identity_fields}
config={
 'plan_id':PLAN_ID,'status':'FINAL_FOR_USER_DISPATCH_TO_CODEX1','created':'2026-10-09',
 'execution_started_by_this_chat':False,'dispatch_to_codex1_authorizes':'technical gate then all MM-DEV scientific runs and analysis; no further scientific-recipe review required',
 'supersedes':['prior GPU-hour thresholds','prior Qwen2.5-VL-3B choice','F1 audit-only stopping point for the newly scoped MM-DEV run'],
 'does_not_modify':['historical audit/engine evidence','historical authorized=false documents','SER-J23 stop decision'],
 'resource':{'gpu_hours_policy':'ACCOUNTING_ONLY','max_allocated_gpu_hours':None,'max_wallclock_hours_for_study':None,'max_gpus_concurrent':5,'gpus_per_worker':1,'gpu_type':'NVIDIA RTX PRO 6000 (match audited device identity)','scheduler_walltime':'site-required allocation lease only; checkpoint and resume without changing scientific horizon','account_qos':'verify current permission; last evidence rose / override-limits-but-killable','resume_after_preemption':True,'gpu_hour_triggered_stop':False},
 'model':identity,'common_start':{'state_id':'S0','source':'audit COMMON_START untouched Qwen3.5-9B','adapter_source':None,'exclude_engineering_adapters':True,'zero_output_lora_initialization_seed':seed_usage()['common_lora_initialization']},
 'scope':{'scientific_stage':'MM-DEV','H':32,'Hp':32,'preparation_runs':4,'states':5,'response_actions':['a0','aP','aC'],'future_repeats':2,'response_runs':30,'scientific_updates':1088,'start_MM_LOCK':False,'start_MM_ONLINE':False,'start_MM_CAL':False,'new_symbolic_training':False},
 'data':{'numeric_sources':'numeric_sources.jsonl','generator_module_sha256':'fd188556668a165498032544fd90316c515e04b449fa44f80b509f8dc505984d','new_materializer_required':True,'scientific_domain':'audited chart-v1; no outcome-adaptive hardening','model_inputs':'image pixels and frozen visible prompt only; no sidecar values/rewards/difficulty labels','axis':[0,100],'integer_values':[10,89],'delta':1,'canvas':[896,672],'minimum_target_gap':5,'operands':{'sum':2,'difference':2,'range':3},'visual_series_counts':{'low':2,'high':4},'numeric_factor':'same audited jointly low/no-carry-no-borrow vs high/carry-borrow for all three operations','root_counts':{'ENGINE_F2':4,'PREP':32,'CONTINUE':64,'PROBE':64,'DEV_EVAL':128},'questions_per_root':24,'images_per_root':8,'new_science_root_counts':288,'split_unit':'complete family (both D levels; all V,chart,operation variants)','deduplication':'global unique ordered first-two target pairs within D and globally unique sorted three-target sets, plus full-source/image identity checks; includes historical audit exclusion'},
 'schedule':{'preparation':'a0; each repeat shares exact stream across A/AP recipes','counts_per_stratum_per_two_updates':{'a0':[2,2,2,2],'aP':[1,3,1,3],'aC':[1,1,3,3]},'cell_order':['LL','HL','LH','HH'],'prompts_per_update':24,'strata_per_update':6,'prompts_per_stratum_per_update':4,'two_update_block_prompts':48,'rounding_remainder':0,'unique_prompts_per_path':768,'shared_continue_streams_across_states':True,'rerank_by_reward_or_loss':False},
 'training':{'algorithm':'single-pass group-relative clipped policy surrogate plus sampled token KL; custom native pinned trainer, not an assumed TRL default','prompts_per_update':24,'group_size':8,'effective_completion_sequences_per_update':192,'gradient_microbatch_sequences':1,'gradient_accumulation_sequences':192,'rollout_policy_frozen_within_update':True,'normalization':'population standard deviation within each prompt group plus 1e-8','normalization_epsilon':1e-8,'clip_epsilon':0.2,'kl_coefficient':0.02,'kl_estimator':'expm1(logp_ref-logp_current)-(logp_ref-logp_current)','kl_reference':'S0 for preparation; frozen exact starting state for each continuation; shared across its actions/repeats','loss_normalization':'mean over generated tokens per sequence, then mean over all 192 sequences','include_eos_in_loss':True,'include_prompt_or_image_tokens_in_loss':False,'generation_reuse':1,'optimizer_updates_per_rollout_set':1,'zero_contrast_groups':'retain; record; no rejection/resampling; still count planned optimizer step','old_logprob_source':'actual raw sampler selected-token log probability; detach; collect at generation before any update','reward_precision':'exact rational equality','preparation_beta':0.5,'rA':'A_full = 1[valid answer equals exact true operation result]','rAP':'0.5*A_full + 0.5*mean_required_reading_exact_correct; mean is 0 if readings field missing/wrong arity','continuation_reward':'rA for all actions','extra_format_or_length_reward':False,'optimizer':{'name':'AdamW','lr':1e-5,'betas':[.9,.999],'eps':1e-8,'weight_decay':0.,'clip_grad_norm':1.,'scheduler':'constant','warmup_updates':0,'fresh_at_each_new_path':True,'restore_full_state_on_resume':True},'lora':{'scope':'language full_attention q_proj/v_proj only; native q includes query+gate','layers':[3,7,11,15,19,23,27,31],'modules':16,'rank':8,'alpha':16,'dropout':0.,'adapter_dtype':'float32','freeze_vision':True,'freeze_projector':True,'freeze_linear_attention':True,'freeze_base':True},'backend':'inherit audited eager BF16 base / FP32 adapter / native unfused linear kernels; no kernel upgrades','worker_forward_mode':'eval with autograd enabled for policy update; dropout disabled'},
 'sampling':{'train':{'do_sample':True,'temperature':1.,'top_p':1.,'top_k':0,'repetition_penalty':1.,'max_new_tokens':192,'enable_thinking':False,'num_beams':1,'all_other_logits_filters':'disabled','use_cache':True,'save_selected_raw_logprobs':True},'probe_eval':{'do_sample':True,'temperature':.7,'top_p':.9,'top_k':0,'repetition_penalty':1.,'max_new_tokens':192,'enable_thinking':False,'K':4,'use_cache':True},'rationale':'training raw sampling and raw ratio identify same mathematical policy; evaluation retains audited channel; training-support conclusions cannot be imported numerically from old top-p audit'},
 'engineering_gate':{'natural_recipe':'same new trainer and rAP, fixed ENGINE_F2 schedule, continuous4 versus independent-process2+2','natural_physical_updates':8,'natural_completion_count':1536,'synthetic_stress_if':'all actual reward groups are constant across the fixed natural engineering trace; actual normalized policy advantages verified zero'
,'nonconstant_reward_but_no_policy_gradient':'GRPO_GRADIENT_MISMATCH technical blocker; synthetic stress is prohibited as an escape','synthetic_stress':'fresh reset; same real generated inputs, coefficient +1 for all sampled sequences in policy surrogate, real reward/normalized advantages still logged but not applied; isolated engineering only','synthetic_physical_updates_if_needed':8,'synthetic_completions_if_needed':1536,'scientific_gradient_evidence_claim':'never call synthetic stress a nonzero natural-reward GRPO result','restore_acceptance':'tensor-exact state and deterministic tokens on identical audited hardware/backend','sampler_teacher_forcing_numeric_gate':{'mean_absolute_logprob_difference_nats_max':.005,'maximum_absolute_logprob_difference_nats_max':.05,'source':'new predeclared engineering tolerances, not observed pass'},'full_effective_batch_test':True,'no_scientific_test_outcomes_used':True,'failure_policy':'technical blocker stops affected new run for explicit repair; successful gate automatically continues to MM-DEV'},
 'measurement':{'primary':'A_full,P_full,J_full over all completed attempts; missing semantic fields count false for corresponding full indicators','joint_table':'P,C,A conditional on joint L; exact six cells, missing not 000','tolerance':'delta/2, diagnostic eight cells only','features_at':'PROBE on each of 5 starting states only','probe_self_scoring':'all 4 completions per question','probe_gold_scoring':'one cached true completion per question per starting state, independent of 4 samples','endpoint_eval':'all 5 starts and all 30 ends; evaluate each identity under its own state ID even if some endpoints coincide','endpoint_field_teacher_forcing':False,'zero_error_S':None,'S_aggregation':'root-equal among supported roots; separately report full-panel undefined status and support counts','context_stability':'separate audit only with within-prompt collision controls; not BGeo main input'},
 'statistics':{'crossfit_root_halves':{'definition':'rank(list(range(128)), crossfit-root-half); first 64 vs last 64; deterministic and no responses used','half0_indices':rank(list(range(128)),'crossfit-root-half')[:64],'half1_indices':rank(list(range(128)),'crossfit-root-half')[64:]},'root_bootstrap_replicates':5000,'root_bootstrap_seed':seed_usage()['bootstrap_seed'],'preserve_within_root':'all 24 variants x K x all state/action/future identities','primary_fixed_path_summary':'mean over 5 registered starts and 2 paired future repeats; conditions on those paths','primary_four_contrasts':['macro_A_aP_minus_a0','macro_A_aC_minus_a0','macro_P_aP_minus_a0','macro_P_aC_minus_a0'],'primary_CI':[.95,.9875],'global_24cell_macro_weights':'1/24; six chart-operation strata 1/6','root_population_inference':'empirical-root descriptive intervals, not independent-training-population CI','future_seed_summary':'both point effects and their differences, not SE from n=2','practical_effect_size_pp':1.0,'no_success_based_extension':True,'adaptive_policy_gap':'exploratory; selection and evaluation split by both future repeat and deterministic root half; no proof of deployable oracle'},
 'utility':{'anchor':'untrained starting state for that path','w':[1/6]*6,'v':[1/6]*6,'lambda':1.,'epsilon_per_protected_stratum':.02,'eta':0.,'cost_unit':'generated tokens, forward sequences, optimizer updates and actual allocated GPU seconds all reported; none subtracted in primary utility','U':'mean(D_A)-mean(max(-D_P,0))','no_train':{'D_A':0.,'D_P':0.,'U':0.,'optimizer_updates':0,'shared_probe_cost':'common decision overhead, not claimed zero total deployment cost'},'feasibility':'D_P per stratum >= -0.02; report point and conditional-root uncertainty separately; not a safety guarantee'},
 'prediction_analysis':{'main_information_candidate':'BNum vs BGeo-S','deliver_complete_input_features':True,'five_state_fit':'only optional fixed exploratory diagnostic, cannot establish new-state generalization','auto_train_controller':False,'independent_MM_LOCK':'not instantiated; requires separate data-source/sample-size and predictor freeze','prohibited_inputs':['path IDs','seed IDs','job IDs','endpoint outputs','future rewards','post-training geometry']},
 'persistence':{'checkpoint_each_committed_update':True,'keep_immutable_updates':[0,8,16,24,32],'rolling_safety_copies':2,'store_mid_rollout_completion_records':True,'commit_idempotently':True,'resume_from_latest_committed_step':'replay saved incomplete-update rollouts under matching policy hash and finish missing logical slots; never count a replay as a new logical sample','retry_new_seed':False,'new_study_gpu_time_stop':False},
 'expected_counts':allocation_counts(),
 'remaining_materialization_fields':['new code commit and source hashes','rendered/processor image hashes','actual named LoRA modules and full zero-output adapter hash','new runtime freeze hash','actual current allocation receipt','new state/endpoint hashes as produced'],
 'remaining_scientific_choices':[],
}
(out/'config/MM_DEV_F2.json').write_text(json.dumps(config,ensure_ascii=False,indent=2)+'\n')
# Minimal evidence copies retain original bytes and relative identity in a manifest.
copies=['START_HERE_FOR_GPT_PRO_zh.md','audit/report/MEASUREMENT_FINDINGS_zh.md','documents/mm_core_f1/NONZERO_RECOVERY_RESULT_20261009_zh.md','documents/mm_core_f1/USER_AMENDMENT_20261008_zh.md','audit/manifests/COMMON_START.json','audit/manifests/PROCESSOR_ENVIRONMENT_LOCK.json']
import shutil,hashlib
manifest=[]
for i,rel in enumerate(copies):
 p=source/rel; target=out/'evidence'/f'E{i+1:02d}_{p.name}';shutil.copyfile(p,target)
 manifest.append({'label':f'E{i+1:02d}','original_archive_path':rel,'local_file':str(target.relative_to(out)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
(out/'evidence/SOURCE_MAP.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n')
print('config/evidence written')
