"""Generate the frozen default plan; this file does not start training."""
from pathlib import Path
import json

OUT=Path(__file__).parent
recipes={
 'R0':[2,0,0,0], 'R1':[0,2,0,0], 'R2':[2,0,1,0], 'R3':[2,0,0,1],
 'R4':[2,0,.5,.5], 'R5':[0,2,1,0], 'R6':[0,2,0,1], 'R7':[0,2,.5,.5]}
dev=[{'seed':61001+i,'role':'development','source_recipe':('R0','R1')[i%2],
      'anchors':[32,96], 'source_steps':96} for i in range(12)]
tune=[{'seed':62001+i,'role':'tuning','source_recipe':('R0','R1')[i%2],
       'anchors':[32,96], 'source_steps':96} for i in range(4)]
cells=[('R0',32),('R0',96),('R1',32),('R1',96)]
test=[{'seed':63001+i,'role':'locked_test','source_recipe':cells[i%4][0],
       'anchors':[cells[i%4][1]], 'source_steps':cells[i%4][1]} for i in range(48)]
def workload(n=12, m=16):
    src=sum(x['source_steps'] for x in dev+tune+test[:n])
    development=32*11*32
    confirm=n*2*9*32
    return {'test_lineages':n,'test_draws':m,'source_updates':src,
      'development_updates':development,'test_updates_upper':confirm,
      'all_updates_upper':src+development+confirm,
      'all_training_outputs_upper':(src+development+confirm)*32,
      'development_branches':352,'test_unique_branches_upper':n*2*9,
      'prestate_outputs':(32+n)*2*72*32,
      'development_H32_outputs':352*144*16,
      'test_H32_outputs_upper':n*2*9*288*m,
      'test_H8_diagnostic_outputs_upper':n*2*9*24*8,
      'historical_E_outputs':16*72*32}
p={
 'protocol':'ssvc-prospective-selection-v2-20260924','status':'DESIGN_NOT_RUN',
 'repository':{'name':'Lhan-chding/dissertation','observed_branch':'codex/decision-modeling-v1-20260919',
   'observed_commit':'b52f55993791a9954be07a0195eb656441b53651',
   'new_branch':'codex/prospective-reward-selection-20260924'},
 'execution':{'max_concurrent_gpu_jobs':5,'preferred_gpu':'NVIDIA RTX PRO 6000',
   'gpus_per_job':1,'allow_four_worker_fallback':True,'ddp_default':False,
   'repeat_full_base_hash':False,'run_full_test_suite_each_branch':False,
   'auto_advance_development':True,'test_requires_frozen_rule_and_predecision':True},
 'model':{'id':'Qwen/Qwen3.5-9B','revision':'c202236235762e1c871ad0ccb60c8ee5ba337b9a',
   'base_dtype':'bfloat16','adapter_config':'INHERIT_MEASURED_D2_CONFIG',
   'lora_initialization_seed':17,'do_not_change_base_model':True},
 'training':{'B':4,'K':8,'branch_steps':32,'source_steps_max':96,
   'max_new_tokens':64,'thinking':False,'temperature':1.0,'top_p':1.0,'top_k':0,
   'sampling_note':'Verify against inherited measured generation contract; mismatch requires bridge, not silent override.',
   'Lnorm':64,'reward_epsilon':1e-4,'clip_epsilon':.2,'gradient_clip':1.0,
   'adamw':{'lr':1e-5,'betas':[.9,.999],'eps':1e-8,'weight_decay':0.0},
   'scheduler':None,'kl_beta':0.0,'ppo_epochs_per_batch':1,
   'explicit_zero_gradient_adam_step':True,'common_arm_schedule':True,
   'source_pool_scenes':384,'branch_pool_scenes':192,
   'source_schedule_seed':73001,'branch_schedule_seeds':[73011,73012],
   'training_rng_excludes_recipe':True,'evaluation_rng_restored':True,
   'test_continuation_repeats':2,'development_continuation_repeats':1,
   'save_source_steps':[0,24,32,88,96], 'save_branch_steps':[0,8,32],
   'resume_checkpoint_every_steps':8},
 'actions':{'channels':['X','A','V','C'],'selectable':recipes,
   'external_baselines':['GDPO_R4','SAW_R4','DIRECT_REPAIR_R4'],
   'direct_repair':{'reward':'R4 - 0.5 * Bdamage','invalid_Bdamage':1.0,
                    'valid_Bdamage':'number_damaged_originally_correct_coordinates / 3'},
   'semantic_fields_used_as_reward_only_in_direct_repair_baseline':True},
 'panels':{'P':{'source':'existing_D2_P','base_scenes':36,'prompts':72,'draws':32,
                 'history_lag_steps':8},
   'D':{'source':'dev','base_scenes':72,'prompts':144,'draws_H32':16,
        'selection_seed':74001},
   'T':{'source':'confirm','base_scenes':144,'prompts':288,'draws_initial':16,
        'draws_choices':[16,32,64], 'selection_seed':74002},
   'T_H8':{'base_scenes':12,'prompts':24,'draws':8,'role':'SECONDARY_DIAGNOSTIC'},
   'historical_E':{'source':'existing_D2_E','prompts':72,'draws':32},
   'base_scene_disjoint':['train','P','D','T'],
   'final_test_panel_read_for_outcomes_only_after_decisions':True},
 'origins':{'development':dev,'tuning':tune,'test_pool':test,
   'test_n_initial':12,'test_n_choices':[12,16,20,24,32,48],
   'test_n_selected_before_any_test_outcome':True,
   'old_D2_origins_role':'HISTORICAL_EXPLORATION_ONLY'},
 'representations':{'levels':['Z0_MOMENTS_GLOBAL','Z1_MOMENTS_STRATIFIED','Z2_REWARD_DISTRIBUTION','Z3_REPAIR_STRUCTURE'],
   'baseline_reward_channels':['X','A','V','C'],
   'reward_histogram':'per-prompt empirical event x exact-rational C histogram',
   'semantic_histogram':'per-prompt sparse joint reward_bin x F x damage_count x edit_count; separate INVALID atom',
   'identities_preserved':True,'forced_low_rank':False,
   'all_levels_receive_same_predecision_samples_and_source_metadata':True,
   'history_weight':.25,'structural_kernel_weight':.5,'nuisance_weight':.25,
   'only_development_feature_scaling':True},
 'selector':{'model':'kernel ridge, action-specific utility deltas to R0',
   'alpha_grid':[.0001,.001,.01,.1,1,10],
   'kernel_ridge_matrix':'K + n_fit * alpha * I',
   'horizon_primary':32,'target_primary':'six-stratum macro pX',
   'target_secondary':'symbolic macro pX','utility_preference_weights':{'pX':1.0},
   'practical_tie':.005,'default_action':'best static recipe chosen on development/tuning, never test',
   'primary_comparison':['Z3_REPAIR_STRUCTURE','Z2_REWARD_DISTRIBUTION'],
   'kernel_histogram':'sqrt empirical frequency inner product; no post-outcome target features',
   'fit_target_scalar_not_full_probability_dynamics':True,
   'confidence_status':'DESCRIPTIVE_NOT_SAFETY_CERTIFICATE'},
 'statistics':{'primary_effect_scale':.01,'alpha':.05,'power_planning':.8,
   'lineage_sd_planning_quantile':.75,'mc_se_fraction_of_effect':.25,
   'primary_sampling':'fixed N and m, frozen before test outcomes',
   'primary_unit':'independent source lineage; average two branch repetitions',
   'fixed_panel_primary_estimand':True,'bootstrap_repetitions':10000,
   'primary_test':'four-cell stratified paired lineage Welch-t interval; within-cell lineage bootstrap sensitivity',
   'sd_unidentified_default_test_n':32,'sd_min_independent_lineages':8,
   'power_planning_anchors':'one predetermined anchor per lineage, never average both source anchors',
   'secondary_Holm_family':['best_static','GDPO_R4','SAW_R4','DIRECT_REPAIR_R4'],
   'all_prompt_simultaneous_noninferiority_gate':False,
   'subgroup_harm_reference':.02,'subgroup_harm_role':'REPORT_NOT_TRAINING_GATE',
   'practical_equivalence_interval':[-.01,.01],
   'allow_optional_stopping_for_significance':False,
   'seed_power_planner':'ceil(((1.96+0.841621)*sd/0.01)**2), round to next allowed N, report residual MDE if >48'},
 'phases':['P0_INFORMATION_AUDIT','P1_IMPLEMENTATION_SMOKE','P2_DEVELOPMENT_MATRIX',
   'P3_FREEZE_SELECTORS','P4_PROSPECTIVE_TEST','P5_ANALYSIS','P6_OPTIONAL_CLOSED_LOOP'],
 'closed_loop':{'default_enabled':False,'reason':'new estimand and trajectories require separate follow-on plan'},
 'workload_min_test':workload(),
 'workload_max_registered_test':workload(48,64),
 'notes':['No new experiments were run by this protocol generator.',
  'GPU counts affect scheduling, never statistical independence.',
  'The optional precision choice changes evaluation count, not training hyperparameters.',
  'Test action deduplication commonly reduces the conservative 9-branch upper bound.']}
(OUT/'protocol.json').write_text(json.dumps(p,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(p['workload_min_test'],ensure_ascii=False,indent=2))
